git:
  depth: false
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_TARGET=android-14
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-26
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- export TERM=dumb
before_install:
- yes | sdkmanager "platforms;android-27"
script:
- "./gradlew asDeb"
notifications:
  email:
    recipients:
    - xwords@eehouse.org
    on_failure: always
